### ISSUE TITLE
not work at all

### ISSUE THREAD

**Issue by ilayanyatto72733** [amka/Spelt#11]
c:\util\spelt-vk>pip install .
Processing c:\util\spelt-vk
Requirement already satisfied (use --upgrade to upgrade): requests in c:\util\python27\lib\site-packages (from Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): vk-api in c:\util\python27\lib\site-packages (from Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): idna<2.6,>=2.5 in c:\util\python27\lib\site-packages (from requests->Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in c:\util\python27\lib\site-packages (from requests->Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in c:\util\python27\lib\site-packages (from requests->Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.22,>=1.21.1 in c:\util\python27\lib\site-packages (from requests->Spelt==0.1)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\util\python27\lib\site-packages (from vk-api->Spelt==0.1)
Installing collected packages: Spelt
  Running setup.py install for Spelt ... done
Successfully installed Spelt-0.1
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

then
c:\util\spelt-vk>spelt --help
Traceback (most recent call last):
  File "C:\util\python27\Scripts\spelt-script.py", line 9, in <module>    load_entry_point('Spelt==0.1', 'console_scripts', 'spelt')()
  File "c:\util\python27\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\util\python27\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "c:\util\python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "c:\util\python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\util\python27\lib\site-packages\spelt\__init__.py", line 24, in <module>
    from spelt.picker import Picker
  File "c:\util\python27\lib\site-packages\spelt\picker.py", line 18, in <module>
    import curses
  File "c:\util\python27\lib\curses\__init__.py", line 15, in <module>    from _curses import *
ImportError: No module named _curses

c:\util\spelt-vk>python --version
Python 2.7.12

How to get this module _curses?

**Comment by ilayanyatto72733** [comment]
fix
[http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses](http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses)
