### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sockwithahole** [amka/Spelt#12]
I'm sorry for what may be a stupid question but I can't figure out this issue. It is likely an issue on my end but if you could help that would be great. I'm not sure if there is any more information I could provide to help. I installed exactly as shown in the readme with pip.
Here is the error I get when running any spelt command:
Traceback (most recent call last):
  File "/usr/bin/spelt", line 11, in <module>
    load_entry_point('Spelt==0.1', 'console_scripts', 'spelt')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/spelt/__init__.py", line 24, in <module>
    from spelt.picker import Picker
  File "/usr/lib/python3.6/site-packages/spelt/picker.py", line 19, in <module>
    import curses.wrapper
ModuleNotFoundError: No module named 'curses.wrapper'

**Comment by sockwithahole** [comment]
Oh shoot. I'm new to github, didn't see the closed issue section, oops.

**Comment by amka** [comment]
Glad to see you found an answer.
