### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by irungentootoo** [amka/Spelt#3]
C:\Users\USER\AppData\Local\Programs\Python\Python36-32\Scripts>spelt.exe --help
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36-32\Scripts\spelt.exe\__main__.py", line 5, in <module>
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\spelt\__init__.py", line 24, in <module>
    from spelt.picker import Picker
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\spelt\picker.py", line 18, in <module>
    import curses
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

C:\Users\USER\AppData\Local\Programs\Python\Python36-32\Scripts>

or i'm do some wrong?

**Comment by amka** [comment]
Unfortunately I can not test it on Windows machine. And as I can see you use compiled version.
How did you build it? Maybe it is described in build-tool documentation?

**Comment by irungentootoo** [comment]
**pip.exe install .**

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\temp\vk-photos-py\Spelt-master>c:\Users\USER\AppData\Local\Programs\Python\Python36-32\Scripts\pip.exe install .
Processing c:\temp\vk-photos-py\spelt-master
  Requirement already satisfied (use --upgrade to upgrade): Spelt==0.1 from file:///C:/temp/vk-photos-py/Spelt-master in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from Spelt==0.1)
Requirement already satisfied: vk-api in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from Spelt==0.1)
Building wheels for collected packages: Spelt
  Running setup.py bdist_wheel for Spelt ... done
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\f9\34\d4\287ded673def5d336ad7dc1cf1a84466ea8653823e97bca5d9
Successfully built Spelt

C:\temp\vk-photos-py\Spelt-master>

**Comment by amka** [comment]
Well, as I can see in python docs windows version of python doesn't include curses package. So there is the problem.

https://docs.python.org/3.3/howto/curses.html
