### ISSUE TITLE
This application doesn't work at all

### ISSUE THREAD

**Issue by Fi5t** [amka/Spelt#6]
When I try to run it I get an error
```
Traceback (most recent call last):
  File "/usr/local/bin/spelt", line 11, in <module>
    load_entry_point('Spelt==0.1', 'console_scripts', 'spelt')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/spelt/__init__.py", line 24, in <module>
    from spelt.picker import Picker
  File "/usr/local/lib/python3.5/site-packages/spelt/picker.py", line 19, in <module>
    import curses.wrapper
ImportError: No module named 'curses.wrapper'
```

**Comment by amka** [comment]
Hi @Fi5t. First of all, do you have a Python [curses](https://docs.python.org/3.5/howto/curses.html) module? And what OS did you use?

**Comment by Fi5t** [comment]
@amka I've solved my trouble. Python3 was the root of all evil =)

**Comment by amka** [comment]
Yeah, my bad. I should write down python version in readme and setup script.
